---@diagnostic disable
return {
    -- UI
    require("plugins.moksha"),
    require("plugins.heirline.init"),
    require("plugins.which-key"),
    require("plugins.simpleindentguides"),
    require("plugins.colorful-winsep"),
    require("plugins.transparent"),
    require("plugins.fix-auto-scroll"),

    -- Functionality
    require("plugins.subversive"),
    require("plugins.guess-indent"),
    require("plugins.autopairs"),
    require("plugins.gx"),
    require("plugins.log-hl"),
    require("plugins.boole"),
    require("plugins.matchparen"),
    require("plugins.marks"),
    require("plugins.pounce"),
    require("plugins.gitsigns"),
    require("plugins.undotree"),
    require("plugins.zincoxide"),
    require("plugins.mini-ai"),
    require("plugins.mini-move"),
    require("plugins.mini-files"),
    require("plugins.oil"),
    require("plugins.fm-nvim"),
    require("plugins.fzf-lua"),
    require("plugins.bigfile"),
    require("plugins.vim-godot"),
    require("plugins.treesj"),
    require("plugins.lsp"),
    require("plugins.blink-cmp"),
}
